name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: scripts/setup.bash
    - name: compile
      run: scripts/build.bash
    - name: test
      run: scripts/run-tests.bash
